### ISSUE TITLE
Readings

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/summer2015#1]

**Comment by MKLau** [comment]
simecol
http://simecol.r-forge.r-project.org

early warning signals
https://github.com/earlywarningtoolbox/earlywarnings-R
http://www.early-warning-signals.org/ealrywarnings-package-in-cran-ready-to-use/

enaR - ecosystem network analysis

double integration and stochastic regime shifts
https://www.youtube.com/watch?v=eXP-wNB3EyY

sirota paper PLoS
http://harvardforest.fas.harvard.edu/sites/harvardforest.fas.harvard.edu/files/ellison-pubs/2013/sirota_etal_2013_PNAS.pdf

Mouquet: http://nicolasmouquet.free.fr/publications/Mouquet%20et%20al%202008%20Func%20Ecol.pdf

**Comment by MKLau** [comment]
1. Hastings, A. (2012) Temporally varying resources amplify the importance of 
   resource input in ecological populations. Biology Letters 8:1067-1069 

http://rsbl.royalsocietypublishing.org/content/roybiolett/8/6/1067.full.pdf
1. Boettiger, C. and Hastings, A. (2013) Tipping points: From patterns to predictions. 
   Nature 493:157-158. 

http://www.nature.com/nature/journal/v493/n7431/full/493157a.html
1. Hastings, A. (2013) Multiple stable states and regime shifts in ecological systems. 
   Mathematics Today February 2013 37-39. 

http://www.ima.org.uk/_db/_documents/Multiple_Stable_States.pdf

**Comment by amellison17** [comment]
Hastings, A. & Wysham, D. Regime shifts in ecological systems can occur with no warning Ecology Letters, 2010, 13, 464-472

http://onlinelibrary.wiley.com/doi/10.1111/j.1461-0248.2010.01439.x/pdf

Thanks, Aaron!

**Comment by MKLau** [comment]
Graham, R. & Tel, T. (1986). Nonequilibrium potentials for coexisting attractors. Phys. Rev. A, 33, 1322–1337.
