### ISSUE TITLE
Generate calendar for the rest of summer

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/summer2015#18]

**Comment by nthnjustice** [comment]
By June 16:
*Complete Lotka-Volterra predator-prey app (test, debug, clean code, deploy)

By June 17:
*Distribute predator-prey app for testing
*Debug pitcher plant simulation

By June 19:
*Build Shiny app for pitcher plant simulation
*Connect with Data Provenance Team
*Read differential equations texts
