### ISSUE TITLE
Matt's Predator-Prey recommendations 

### ISSUE THREAD

**Issue by nthnjustice** [HarvardForest/summer2015#25]
Implement recommendations from Matt.

**Comment by MKLau** [comment]
I would like it if we could decide on the best settings for the breakpoint and EWS analyses and just give the user a single button to click that will display the output (e.g., overlay the breakpoints, produce the relevant stats, show the EWS plots, etc.)
- Combine breakpoint and ews analyses into a single tab
- Add plot assets to mainPlot
- Build edit parameter feature as separate tab
- Autorefresh analyses with parameter change

**Comment by MKLau** [comment]
Let's set bounds for the length of time.
- Add helpText

**Comment by MKLau** [comment]
State variables that are integer might be better represented as sliders. 
- Skip for now

**Comment by MKLau** [comment]
The data table feature is awesome. Need to be have all values displayed to be fully functional.
- Look if cap can be edited
- Implement download data table feature

**Comment by MKLau** [comment]
Change the "Graph" tab to "Model"
- Skip for now

**Comment by MKLau** [comment]
We should validate these values. Look in intro modeling text.
- Yes Do that
