### ISSUE TITLE
Breakpoint winsize 

### ISSUE THREAD

**Issue by nthnjustice** [HarvardForest/summer2015#41]
(With the Pitcher Plant app)

Rolling window size of 10 (=10%) with 2 days worth of time series data crashes. However, a rolling window of size 10 works with 5 days worth of time series data. There seems to be a threshold or bound for the allowable size of the rolling window based on the size of the time series length. This error occurs with both the quick and advanced breakpoint analysis. 

(Fiddling with parameters and arguments supports this hypothesis.)

?How to handle this?

**Comment by MKLau** [comment]
It might not be an app issue. If you haven't already, try the same analysis (10% for 2 and 5 days) just in R not the app.
